# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170412_2208'),
        ('music', '0008_album_user'),
    ]

    operations = [
    ]
